---
micronaut:
  application:
    name: employeeorm

---
datasources:
  default:
    url: jdbc:postgresql://localhost:26257/companies
    driverClassName: org.postgresql.Driver
    username: root
    password: ""
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

