micronaut:
  application:
    name: employee
  database:
    host: localhost
    user: root
    pass: root
    name: companies
datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: root
        password: root
        driverClassName: org.h2.Driver
        name: companies
